dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.5.6"
  - "3.6.3"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -U pip
  - pip -q install -r t2i/tests/test_requirements.txt
  # - pip install -e .

  # dev dependencies
  - pip install coverage
  - pip install coveralls
  - pip install pytorch
  - pip install tensorflow
  - pip install numpy

script:
  - python -m unittest discover -v t2i "*_test.py"
  - coverage run -m unittest discover -v t2i "*_test.py"
  - coverage report --skip-covered
  - coveralls
