dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -U pip
  - pip -q install -r requirements.txt
  # - pip install -e .

  # dev dependencies
  - pip install coverage
  - pip install coveralls

script:
  # Unit test
  - python -m unittest discover -v t2i "*_test.py"
  - coverage run -m unittest discover -v t2i "*_test.py"
  - coverage report --skip-covered
  - coveralls