dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.5.6"
  - "3.6.3"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -U pip
  # - pip install -e .

  # dev dependencies
  - pip install coverage
  - pip install coveralls
  - pip install torch
  - pip install tensorflow
  - pip install numpy

script:
  - coverage run --source=t2i -m unittest discover -v t2i "t2i_test.py"
  - coverage report --skip-covered
  - coveralls
