dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.5.6"
  - "3.6.3"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -U pip
  # - pip install -e .

  # dev dependencies
  - pip install coverage
  - pip install coveralls

script:
  # Unit test - first run without external libraries
  - python -m unittest discover -v t2i "*_test.py"
  # Now with other libraries
  - pip -q install -r t2i/tests/test_requirements.txt
  - coverage run -m unittest discover -v t2i "*_test.py"
  - coverage report --skip-covered
  - coveralls
